"""add raw_data to import_batches

Revision ID: 1f59beed3111
Revises: final_fix_all_rev
Create Date: 2026-09-10 10:22:35.095660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1f59beed3111'
down_revision: Union[str, None] = 'final_fix_all_rev'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ew_group_proposals_actor_id', table_name='ew_group_proposals')
    op.drop_index('ix_ew_group_proposals_ew_group_id', table_name='ew_group_proposals')
    op.drop_index('ix_ew_group_proposals_status', table_name='ew_group_proposals')
    op.drop_table('ew_group_proposals')
    op.drop_column('ew_groups', 'supersedes_id')
    op.drop_column('ew_groups', 'status')
    op.add_column('import_batches', sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_constraint('platform_emitter_links_emitter_id_fkey', 'platform_emitter_links', type_='foreignkey')
    op.create_foreign_key(None, 'platform_emitter_links', 'emitters', ['emitter_id'], ['id'], ondelete='CASCADE')
    op.drop_column('platforms', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platforms', sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'draft'::character varying"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'platform_emitter_links', type_='foreignkey')
    op.create_foreign_key('platform_emitter_links_emitter_id_fkey', 'platform_emitter_links', 'emitters', ['emitter_id'], ['id'])
    op.drop_column('import_batches', 'raw_data')
    op.add_column('ew_groups', sa.Column('status', postgresql.ENUM('approved', 'draft', 'superseded', 'rejected', name='ewgroupstatus'), server_default=sa.text("'approved'::ewgroupstatus"), autoincrement=False, nullable=False))
    op.add_column('ew_groups', sa.Column('supersedes_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_table('ew_group_proposals',
    sa.Column('ew_group_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('proposed_changes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name='ew_group_proposals_actor_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ew_group_id'], ['ew_groups.id'], name='ew_group_proposals_ew_group_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='ew_group_proposals_pkey')
    )
    op.create_index('ix_ew_group_proposals_status', 'ew_group_proposals', ['status'], unique=False)
    op.create_index('ix_ew_group_proposals_ew_group_id', 'ew_group_proposals', ['ew_group_id'], unique=False)
    op.create_index('ix_ew_group_proposals_actor_id', 'ew_group_proposals', ['actor_id'], unique=False)
    # ### end Alembic commands ###
