"""add_details_to_mode_elements

Revision ID: 21501ac80f20
Revises: 1f59beed3111
Create Date: 2026-09-10 10:58:40.470985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '21501ac80f20'
down_revision: Union[str, None] = '1f59beed3111'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_batches', 'raw_data')
    op.add_column('mode_elements', sa.Column('details', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mode_elements', 'details')
    op.add_column('import_batches', sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
