"""mode_drafts_and_test_derivation

Revision ID: 472c241a83c4
Revises: ecb2e5dedaa9
Create Date: 2026-08-28 12:52:09.113300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '472c241a83c4'
down_revision: Union[str, None] = 'ecb2e5dedaa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


mode_status_enum = sa.Enum('approved', 'draft', 'superseded', 'rejected', name='modestatus')
link_type_enum = sa.Enum('exercised', 'derived', name='testrecordmodelinktype')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    mode_status_enum.create(bind, checkfirst=True)
    link_type_enum.create(bind, checkfirst=True)
    op.add_column('modes', sa.Column('status', mode_status_enum, server_default='approved', nullable=False))
    op.add_column('modes', sa.Column('supersedes_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_modes_supersedes_id'), 'modes', ['supersedes_id'], unique=False)
    op.create_foreign_key(None, 'modes', 'modes', ['supersedes_id'], ['id'], ondelete='SET NULL')
    op.add_column('test_record_modes', sa.Column('link_type', link_type_enum, server_default='exercised', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_record_modes', 'link_type')
    op.drop_constraint(None, 'modes', type_='foreignkey')
    op.drop_index(op.f('ix_modes_supersedes_id'), table_name='modes')
    op.drop_column('modes', 'supersedes_id')
    op.drop_column('modes', 'status')
    bind = op.get_bind()
    link_type_enum.drop(bind, checkfirst=True)
    mode_status_enum.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
