"""add notes to emitters and sources

Revision ID: 6ef6d282f7c4
Revises: c020a1532c82
Create Date: 2026-09-14 14:32:25.082767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6ef6d282f7c4'
down_revision: Union[str, None] = 'c020a1532c82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emitters', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('sources', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'notes')
    op.drop_column('emitters', 'notes')
    # ### end Alembic commands ###
