"""phase5_mdfs_and_test_records

Revision ID: 7dce96dbceff
Revises: e6cb2cbe3435
Create Date: 2026-08-24 08:06:22.993602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '7dce96dbceff'
down_revision: Union[str, None] = 'e6cb2cbe3435'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mdfs',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'pending_review', 'approved', 'released', 'deprecated', name='mdfstatus'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mdfs_name'), 'mdfs', ['name'], unique=True)
    op.create_table('mdf_versions',
    sa.Column('mdf_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mdf_id'], ['mdfs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mdf_id', 'version_number', name='uq_mdf_version_number')
    )
    op.create_index(op.f('ix_mdf_versions_mdf_id'), 'mdf_versions', ['mdf_id'], unique=False)
    op.create_table('mdf_platform_links',
    sa.Column('mdf_id', sa.UUID(), nullable=False),
    sa.Column('platform_id', sa.UUID(), nullable=False),
    sa.Column('platform_version_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['mdf_id'], ['mdfs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.ForeignKeyConstraint(['platform_version_id'], ['platform_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mdf_id', 'platform_id', name='uq_mdf_platform')
    )
    op.create_index(op.f('ix_mdf_platform_links_mdf_id'), 'mdf_platform_links', ['mdf_id'], unique=False)
    op.create_table('test_records',
    sa.Column('scope_type', sa.Enum('emitter', 'mdf', name='testscopetype'), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=False),
    sa.Column('emitter_version_id', sa.UUID(), nullable=True),
    sa.Column('mdf_version_id', sa.UUID(), nullable=True),
    sa.Column('test_type', sa.Enum('simulation', 'lab_bench', 'live_range', 'field_exercise', name='testtype'), nullable=False),
    sa.Column('result', sa.Enum('pass_', 'fail', 'partial', 'inconclusive', name='testresult'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tested_by', sa.UUID(), nullable=True),
    sa.Column('test_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['emitter_version_id'], ['emitter_versions.id'], ),
    sa.ForeignKeyConstraint(['mdf_version_id'], ['mdf_versions.id'], ),
    sa.ForeignKeyConstraint(['tested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_records_scope_id'), 'test_records', ['scope_id'], unique=False)
    op.create_table('test_record_modes',
    sa.Column('test_record_id', sa.UUID(), nullable=False),
    sa.Column('mode_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['mode_id'], ['modes.id'], ),
    sa.ForeignKeyConstraint(['test_record_id'], ['test_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_record_modes_test_record_id'), 'test_record_modes', ['test_record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_record_modes_test_record_id'), table_name='test_record_modes')
    op.drop_table('test_record_modes')
    op.drop_index(op.f('ix_test_records_scope_id'), table_name='test_records')
    op.drop_table('test_records')
    op.drop_index(op.f('ix_mdf_platform_links_mdf_id'), table_name='mdf_platform_links')
    op.drop_table('mdf_platform_links')
    op.drop_index(op.f('ix_mdf_versions_mdf_id'), table_name='mdf_versions')
    op.drop_table('mdf_versions')
    op.drop_index(op.f('ix_mdfs_name'), table_name='mdfs')
    op.drop_table('mdfs')
    # ### end Alembic commands ###
