"""test_record_retest_link

Revision ID: 836515fbc694
Revises: e095882048be
Create Date: 2026-08-28 15:36:13.283064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '836515fbc694'
down_revision: Union[str, None] = 'e095882048be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_records', sa.Column('retests_test_record_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'test_records', 'test_records', ['retests_test_record_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_records', type_='foreignkey')
    op.drop_column('test_records', 'retests_test_record_id')
    # ### end Alembic commands ###
