"""Sync database schema

Revision ID: 9621f10ca8cd
Revises: a867083eef27
Create Date: 2026-09-15 10:51:59.107428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9621f10ca8cd'
down_revision: Union[str, None] = 'a867083eef27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
