"""phase6_ambiguity

Revision ID: ad5606655dc9
Revises: 7dce96dbceff
Create Date: 2026-08-24 08:19:57.867926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ad5606655dc9'
down_revision: Union[str, None] = '7dce96dbceff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ambiguity_runs',
    sa.Column('scope_type', sa.Enum('emitter', 'platform', 'mdf', name='ambiguityscopetype'), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=False),
    sa.Column('emitter_version_id', sa.UUID(), nullable=True),
    sa.Column('platform_version_id', sa.UUID(), nullable=True),
    sa.Column('mdf_version_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'complete', 'failed', name='ambiguityrunstatus'), nullable=False),
    sa.Column('tolerance_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['emitter_version_id'], ['emitter_versions.id'], ),
    sa.ForeignKeyConstraint(['mdf_version_id'], ['mdf_versions.id'], ),
    sa.ForeignKeyConstraint(['platform_version_id'], ['platform_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ambiguity_runs_scope_id'), 'ambiguity_runs', ['scope_id'], unique=False)
    op.create_index(op.f('ix_ambiguity_runs_scope_type'), 'ambiguity_runs', ['scope_type'], unique=False)
    op.create_table('ambiguity_findings',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('mode_id_a', sa.UUID(), nullable=False),
    sa.Column('mode_id_b', sa.UUID(), nullable=False),
    sa.Column('rf_overlap_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('pw_overlap_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('pri_overlap_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pri_comparison_type', sa.String(length=50), nullable=False),
    sa.Column('combined_severity', sa.Enum('none', 'low', 'medium', 'high', 'exact_overlap', name='ambiguityseverity'), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewer_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['ambiguity_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ambiguity_findings_run_id'), 'ambiguity_findings', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ambiguity_findings_run_id'), table_name='ambiguity_findings')
    op.drop_table('ambiguity_findings')
    op.drop_index(op.f('ix_ambiguity_runs_scope_type'), table_name='ambiguity_runs')
    op.drop_index(op.f('ix_ambiguity_runs_scope_id'), table_name='ambiguity_runs')
    op.drop_table('ambiguity_runs')
    # ### end Alembic commands ###
