"""import_batches_and_parameter_sequences

Revision ID: b0413a33e335
Revises: 836515fbc694
Create Date: 2026-08-28 17:37:03.885967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b0413a33e335'
down_revision: Union[str, None] = '836515fbc694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


element_variant_enum = sa.Enum('typical', 'discrete', 'most_probable', 'extreme', name='elementvariant')
source_status_enum = sa.Enum('approved', 'pending_review', 'rejected', name='sourcestatus')


def upgrade() -> None:
    bind = op.get_bind()
    # 'elementvariant' does NOT need an explicit create here: it's used as a
    # column type on the brand-new 'parameter_sequences' table below, and
    # create_table's own before_create DDL event creates enum types it
    # references automatically (unconditionally — pre-creating it here too
    # would collide with that and raise DuplicateObject).
    #
    # 'sourcestatus' DOES need one: it's only ever used via add_column onto
    # the already-existing 'sources' table, which does not trigger that
    # automatic per-table type-creation event.
    source_status_enum.create(bind, checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batches',
    sa.Column('emitter_id', sa.UUID(), nullable=False),
    sa.Column('document_name', sa.String(length=300), nullable=False),
    sa.Column('document_reference', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['emitter_id'], ['emitters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_batches_emitter_id'), 'import_batches', ['emitter_id'], unique=False)
    op.create_table('parameter_sequences',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('variant', sa.Enum('typical', 'discrete', 'most_probable', 'extreme', name='elementvariant'), nullable=True),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parameter_sequences_source_id'), 'parameter_sequences', ['source_id'], unique=False)
    op.add_column('mode_elements', sa.Column('variant', sa.Enum('typical', 'discrete', 'most_probable', 'extreme', name='elementvariant'), nullable=True))
    op.add_column('sources', sa.Column('status', sa.Enum('approved', 'pending_review', 'rejected', name='sourcestatus'), server_default='approved', nullable=False))
    op.add_column('sources', sa.Column('import_batch_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_sources_import_batch_id'), 'sources', ['import_batch_id'], unique=False)
    op.create_foreign_key(None, 'sources', 'import_batches', ['import_batch_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    # New Element parameter type — not auto-detected by autogenerate (enum
    # member changes aren't part of the SQLAlchemy metadata diff). Must run
    # outside the migration's transaction on Postgres.
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE elementtype ADD VALUE IF NOT EXISTS 'scan'")


def downgrade() -> None:
    # Note: Postgres cannot drop a single enum value, so the 'scan' label added
    # to elementtype in upgrade() is NOT removed here — accepted one-way tradeoff.

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sources', type_='foreignkey')
    op.drop_index(op.f('ix_sources_import_batch_id'), table_name='sources')
    op.drop_column('sources', 'import_batch_id')
    op.drop_column('sources', 'status')
    op.drop_column('mode_elements', 'variant')
    op.drop_index(op.f('ix_parameter_sequences_source_id'), table_name='parameter_sequences')
    op.drop_table('parameter_sequences')
    op.drop_index(op.f('ix_import_batches_emitter_id'), table_name='import_batches')
    op.drop_table('import_batches')
    # ### end Alembic commands ###

    bind = op.get_bind()
    source_status_enum.drop(bind, checkfirst=True)
    element_variant_enum.drop(bind, checkfirst=True)
