"""phase1_initial_schema

Revision ID: bbb634bef582
Revises: 
Create Date: 2026-08-24 07:19:45.288327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'bbb634bef582'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'editor', 'viewer', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('emitters',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('designation', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'in_review', 'validated', 'deprecated', name='emitterstatus'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emitters_name'), 'emitters', ['name'], unique=True)
    op.create_table('ew_groups',
    sa.Column('emitter_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('scan_min', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('scan_max', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('threat_priority', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['emitter_id'], ['emitters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ew_groups_emitter_id'), 'ew_groups', ['emitter_id'], unique=False)
    op.create_table('sources',
    sa.Column('emitter_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_date', sa.Date(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['emitter_id'], ['emitters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_emitter_id'), 'sources', ['emitter_id'], unique=False)
    op.create_table('mode_elements',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('element_type', sa.Enum('rf', 'pw', 'pri', name='elementtype'), nullable=False),
    sa.Column('value_min', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('value_max', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('stagger_values', sa.ARRAY(sa.Numeric(precision=14, scale=4)), nullable=True),
    sa.Column('jitter_min', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('jitter_max', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mode_elements_source_id'), 'mode_elements', ['source_id'], unique=False)
    op.create_table('modes',
    sa.Column('ew_group_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('pri_type', sa.Enum('fixed', 'stagger', 'cw', 'xlet', name='pritype'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ew_group_id'], ['ew_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modes_ew_group_id'), 'modes', ['ew_group_id'], unique=False)
    op.create_index(op.f('ix_modes_source_id'), 'modes', ['source_id'], unique=False)
    op.create_table('mode_lines',
    sa.Column('mode_id', sa.UUID(), nullable=False),
    sa.Column('rf_min_mhz', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('rf_max_mhz', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('pw_min_us', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('pw_max_us', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('pri_min_us', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('pri_max_us', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('jitter_min_us', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('jitter_max_us', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('pri_stagger_values_us', sa.ARRAY(sa.Numeric(precision=14, scale=4)), nullable=True),
    sa.Column('type_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dsl_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['mode_id'], ['modes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mode_lines_mode_id'), 'mode_lines', ['mode_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mode_lines_mode_id'), table_name='mode_lines')
    op.drop_table('mode_lines')
    op.drop_index(op.f('ix_modes_source_id'), table_name='modes')
    op.drop_index(op.f('ix_modes_ew_group_id'), table_name='modes')
    op.drop_table('modes')
    op.drop_index(op.f('ix_mode_elements_source_id'), table_name='mode_elements')
    op.drop_table('mode_elements')
    op.drop_index(op.f('ix_sources_emitter_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_ew_groups_emitter_id'), table_name='ew_groups')
    op.drop_table('ew_groups')
    op.drop_index(op.f('ix_emitters_name'), table_name='emitters')
    op.drop_table('emitters')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
