"""add test_line sort_order

Revision ID: d1f3db48d5f8
Revises: a3c1f9e2b7d4
Create Date: 2026-09-22 19:26:35.661540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd1f3db48d5f8'
down_revision: Union[str, None] = 'a3c1f9e2b7d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_lines', sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###

    # Backfill: existing rows all default to 0 (tied), which falls back to
    # created_at — and rows imported together in one batch share the same
    # transaction-time created_at in Postgres, so those ties display in
    # whatever arbitrary order the table scan happens to return. Assign a
    # stable per-emitter order now (created_at, then id, as the best
    # available tiebreak — true paste order isn't recoverable for rows
    # imported before this column existed).
    op.execute(
        """
        UPDATE test_lines
        SET sort_order = ranked.rn
        FROM (
            SELECT id, ROW_NUMBER() OVER (PARTITION BY emitter_id ORDER BY created_at, id) - 1 AS rn
            FROM test_lines
        ) AS ranked
        WHERE test_lines.id = ranked.id
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_lines', 'sort_order')
    # ### end Alembic commands ###
