"""cascade_delete_test_record_mode_link

Revision ID: d3265fb54f12
Revises: b60655d549cf
Create Date: 2026-08-26 11:24:45.898199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd3265fb54f12'
down_revision: Union[str, None] = 'b60655d549cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('test_record_modes_mode_id_fkey', 'test_record_modes', type_='foreignkey')
    op.create_foreign_key(None, 'test_record_modes', 'modes', ['mode_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_record_modes', type_='foreignkey')
    op.create_foreign_key('test_record_modes_mode_id_fkey', 'test_record_modes', 'modes', ['mode_id'], ['id'])
    # ### end Alembic commands ###
