"""baseline schema

Revision ID: d68a4d14b7c2
Revises: 
Create Date: 2026-09-18 11:23:01.796619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd68a4d14b7c2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('source_groups',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'editor', 'viewer', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('emitters',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('designation', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'in_review', 'validated', 'deprecated', name='emitterstatus'), nullable=False),
    sa.Column('rework_note', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('checked_out_by_id', sa.UUID(), nullable=True),
    sa.Column('checked_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('forked_from_emitter_id', sa.UUID(), nullable=True),
    sa.Column('forked_from_version_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['checked_out_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['forked_from_emitter_id'], ['emitters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emitters_checked_out_by_id'), 'emitters', ['checked_out_by_id'], unique=False)
    op.create_index(op.f('ix_emitters_forked_from_emitter_id'), 'emitters', ['forked_from_emitter_id'], unique=False)
    op.create_index(op.f('ix_emitters_forked_from_version_id'), 'emitters', ['forked_from_version_id'], unique=False)
    op.create_index(op.f('ix_emitters_name'), 'emitters', ['name'], unique=True)
    op.create_table('mdfs',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'pending_review', 'approved', 'released', 'deprecated', name='mdfstatus'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mdfs_customer_id'), 'mdfs', ['customer_id'], unique=False)
    op.create_index(op.f('ix_mdfs_name'), 'mdfs', ['name'], unique=True)
    op.create_table('platforms',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platforms_name'), 'platforms', ['name'], unique=True)
    op.create_table('audit_log',
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Enum('create', 'update', 'delete', 'restore', 'status_change', 'commit', 'login', 'login_failed', 'logout', 'checkout', 'checkin', 'discard', 'revert', 'fork', name='auditaction'), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('emitter_id', sa.UUID(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['emitter_id'], ['emitters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_emitter_id'), 'audit_log', ['emitter_id'], unique=False)
    op.create_index('ix_audit_log_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_type'), 'audit_log', ['entity_type'], unique=False)
    op.create_table('emitter_notes',
    sa.Column('emitter_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['emitter_id'], ['emitters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emitter_notes_created_at'), 'emitter_notes', ['created_at'], unique=False)
    op.create_index(op.f('ix_emitter_notes_emitter_id'), 'emitter_notes', ['emitter_id'], unique=False)
    op.create_table('emitter_versions',
    sa.Column('emitter_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['emitter_id'], ['emitters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('emitter_id', 'version_number', name='uq_emitter_version_number')
    )
    op.create_index(op.f('ix_emitter_versions_emitter_id'), 'emitter_versions', ['emitter_id'], unique=False)
    op.create_table('ew_groups',
    sa.Column('emitter_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('scan_min', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('scan_max', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('scan_delta', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('threat_priority', sa.Integer(), nullable=True),
    sa.Column('ageout', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['emitter_id'], ['emitters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ew_groups_emitter_id'), 'ew_groups', ['emitter_id'], unique=False)
    op.create_table('function_groups',
    sa.Column('emitter_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['emitter_id'], ['emitters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_function_groups_emitter_id'), 'function_groups', ['emitter_id'], unique=False)
    op.create_table('import_batches',
    sa.Column('emitter_id', sa.UUID(), nullable=False),
    sa.Column('document_name', sa.String(length=300), nullable=False),
    sa.Column('document_reference', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['emitter_id'], ['emitters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_batches_emitter_id'), 'import_batches', ['emitter_id'], unique=False)
    op.create_table('intercepts',
    sa.Column('emitter_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['emitter_id'], ['emitters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intercepts_emitter_id'), 'intercepts', ['emitter_id'], unique=False)
    op.create_table('mdf_notes',
    sa.Column('mdf_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mdf_id'], ['mdfs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mdf_notes_created_at'), 'mdf_notes', ['created_at'], unique=False)
    op.create_index(op.f('ix_mdf_notes_mdf_id'), 'mdf_notes', ['mdf_id'], unique=False)
    op.create_table('mdf_versions',
    sa.Column('mdf_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mdf_id'], ['mdfs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mdf_id', 'version_number', name='uq_mdf_version_number')
    )
    op.create_index(op.f('ix_mdf_versions_mdf_id'), 'mdf_versions', ['mdf_id'], unique=False)
    op.create_table('platform_versions',
    sa.Column('platform_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_id', 'version_number', name='uq_platform_version_number')
    )
    op.create_index(op.f('ix_platform_versions_platform_id'), 'platform_versions', ['platform_id'], unique=False)
    op.create_table('ambiguity_runs',
    sa.Column('scope_type', sa.Enum('emitter', 'platform', 'mdf', name='ambiguityscopetype'), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=False),
    sa.Column('emitter_version_id', sa.UUID(), nullable=True),
    sa.Column('platform_version_id', sa.UUID(), nullable=True),
    sa.Column('mdf_version_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'complete', 'failed', name='ambiguityrunstatus'), nullable=False),
    sa.Column('tolerance_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['emitter_version_id'], ['emitter_versions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mdf_version_id'], ['mdf_versions.id'], ),
    sa.ForeignKeyConstraint(['platform_version_id'], ['platform_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ambiguity_runs_scope_id'), 'ambiguity_runs', ['scope_id'], unique=False)
    op.create_index(op.f('ix_ambiguity_runs_scope_type'), 'ambiguity_runs', ['scope_type'], unique=False)
    op.create_table('intercept_entries',
    sa.Column('intercept_id', sa.UUID(), nullable=False),
    sa.Column('pri_type', sa.Enum('fixed', 'stagger', 'cw', 'xlet', name='pritype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('rf_min_mhz', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('rf_max_mhz', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('rf_mean_mhz', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('pw_min_us', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('pw_max_us', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('pw_mean_us', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('pri_min_us', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('pri_max_us', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('pri_mean_us', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('jitter_mean_us', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('stagger_values', sa.ARRAY(sa.Numeric(precision=14, scale=4)), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['intercept_id'], ['intercepts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intercept_entries_created_at'), 'intercept_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_intercept_entries_intercept_id'), 'intercept_entries', ['intercept_id'], unique=False)
    op.create_table('intercept_notes',
    sa.Column('intercept_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['intercept_id'], ['intercepts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intercept_notes_created_at'), 'intercept_notes', ['created_at'], unique=False)
    op.create_index(op.f('ix_intercept_notes_intercept_id'), 'intercept_notes', ['intercept_id'], unique=False)
    op.create_table('mdf_platform_links',
    sa.Column('mdf_id', sa.UUID(), nullable=False),
    sa.Column('platform_id', sa.UUID(), nullable=False),
    sa.Column('platform_version_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['mdf_id'], ['mdfs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.ForeignKeyConstraint(['platform_version_id'], ['platform_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mdf_id', 'platform_id', name='uq_mdf_platform')
    )
    op.create_index(op.f('ix_mdf_platform_links_mdf_id'), 'mdf_platform_links', ['mdf_id'], unique=False)
    op.create_table('platform_emitter_links',
    sa.Column('platform_id', sa.UUID(), nullable=False),
    sa.Column('emitter_id', sa.UUID(), nullable=False),
    sa.Column('emitter_version_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['emitter_id'], ['emitters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['emitter_version_id'], ['emitter_versions.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_id', 'emitter_id', name='uq_platform_emitter')
    )
    op.create_index(op.f('ix_platform_emitter_links_platform_id'), 'platform_emitter_links', ['platform_id'], unique=False)
    op.create_table('sources',
    sa.Column('emitter_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rf_legacy_term', sa.Text(), nullable=True),
    sa.Column('pri_legacy_term', sa.Text(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('approved', 'pending_review', 'rejected', name='sourcestatus'), server_default='approved', nullable=False),
    sa.Column('import_batch_id', sa.UUID(), nullable=True),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['emitter_id'], ['emitters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['source_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_batch_id'], ['import_batches.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_emitter_id'), 'sources', ['emitter_id'], unique=False)
    op.create_index(op.f('ix_sources_group_id'), 'sources', ['group_id'], unique=False)
    op.create_index(op.f('ix_sources_import_batch_id'), 'sources', ['import_batch_id'], unique=False)
    op.create_index(op.f('ix_sources_source_type'), 'sources', ['source_type'], unique=False)
    op.create_table('test_records',
    sa.Column('scope_type', sa.Enum('emitter', 'mdf', name='testscopetype'), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=False),
    sa.Column('emitter_version_id', sa.UUID(), nullable=True),
    sa.Column('mdf_version_id', sa.UUID(), nullable=True),
    sa.Column('test_type', sa.Enum('simulation', 'lab_bench', 'live_range', 'field_exercise', 'intercept', name='testtype'), nullable=False),
    sa.Column('result', sa.Enum('pass_', 'fail', 'partial', 'inconclusive', name='testresult'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tested_by', sa.UUID(), nullable=True),
    sa.Column('test_date', sa.Date(), nullable=False),
    sa.Column('simulation_created_date', sa.Date(), nullable=True),
    sa.Column('retests_test_record_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['emitter_version_id'], ['emitter_versions.id'], ),
    sa.ForeignKeyConstraint(['mdf_version_id'], ['mdf_versions.id'], ),
    sa.ForeignKeyConstraint(['retests_test_record_id'], ['test_records.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tested_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_records_scope_id'), 'test_records', ['scope_id'], unique=False)
    op.create_table('ambiguity_findings',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('mode_id_a', sa.UUID(), nullable=False),
    sa.Column('mode_id_b', sa.UUID(), nullable=False),
    sa.Column('rf_overlap_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('pw_overlap_pct', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('pri_overlap_pct', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('pri_comparison_type', sa.String(length=50), nullable=False),
    sa.Column('combined_severity', sa.Enum('none', 'low', 'medium', 'high', 'exact_overlap', name='ambiguityseverity'), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewer_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['ambiguity_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ambiguity_findings_run_id'), 'ambiguity_findings', ['run_id'], unique=False)
    op.create_table('mode_elements',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('element_type', sa.Enum('rf', 'pw', 'pri', 'scan', name='elementtype'), nullable=False),
    sa.Column('variant', sa.Enum('typical', 'discrete', 'most_probable', 'extreme', 'intercept', 'analysis', 'other', name='elementvariant'), nullable=True),
    sa.Column('value_min', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('value_max', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('stagger_values', sa.ARRAY(sa.Numeric(precision=14, scale=4)), nullable=True),
    sa.Column('jitter_min', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('jitter_max', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('delta', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mode_elements_source_id'), 'mode_elements', ['source_id'], unique=False)
    op.create_table('mode_generation_batches',
    sa.Column('ew_group_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('name_prefix', sa.String(length=200), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ew_group_id'], ['ew_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mode_generation_batches_ew_group_id'), 'mode_generation_batches', ['ew_group_id'], unique=False)
    op.create_index(op.f('ix_mode_generation_batches_source_id'), 'mode_generation_batches', ['source_id'], unique=False)
    op.create_table('parameter_sequences',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('variant', sa.Enum('typical', 'discrete', 'most_probable', 'extreme', 'intercept', 'analysis', 'other', name='elementvariant'), nullable=True),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('rf_delta', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('pw_delta', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('pri_delta', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parameter_sequences_source_id'), 'parameter_sequences', ['source_id'], unique=False)
    op.create_table('source_notes',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_notes_created_at'), 'source_notes', ['created_at'], unique=False)
    op.create_index(op.f('ix_source_notes_source_id'), 'source_notes', ['source_id'], unique=False)
    op.create_table('test_record_function_groups',
    sa.Column('test_record_id', sa.UUID(), nullable=False),
    sa.Column('function_group_id', sa.UUID(), nullable=False),
    sa.Column('computed_result', sa.Enum('pass_', 'fail', 'partial', 'inconclusive', name='testresult'), nullable=False),
    sa.Column('override_result', sa.Enum('pass_', 'fail', 'partial', 'inconclusive', name='testresult'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['function_group_id'], ['function_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_record_id'], ['test_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_record_function_groups_function_group_id'), 'test_record_function_groups', ['function_group_id'], unique=False)
    op.create_index(op.f('ix_test_record_function_groups_test_record_id'), 'test_record_function_groups', ['test_record_id'], unique=False)
    op.create_table('modes',
    sa.Column('ew_group_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('pri_type', sa.Enum('fixed', 'stagger', 'cw', 'xlet', name='pritype'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('generation_batch_id', sa.UUID(), nullable=True),
    sa.Column('function_group_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ew_group_id'], ['ew_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['function_group_id'], ['function_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['generation_batch_id'], ['mode_generation_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modes_ew_group_id'), 'modes', ['ew_group_id'], unique=False)
    op.create_index(op.f('ix_modes_function_group_id'), 'modes', ['function_group_id'], unique=False)
    op.create_index(op.f('ix_modes_generation_batch_id'), 'modes', ['generation_batch_id'], unique=False)
    op.create_index(op.f('ix_modes_source_id'), 'modes', ['source_id'], unique=False)
    op.create_table('intercept_entry_modes',
    sa.Column('intercept_entry_id', sa.UUID(), nullable=False),
    sa.Column('mode_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['intercept_entry_id'], ['intercept_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mode_id'], ['modes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intercept_entry_modes_intercept_entry_id'), 'intercept_entry_modes', ['intercept_entry_id'], unique=False)
    op.create_index(op.f('ix_intercept_entry_modes_mode_id'), 'intercept_entry_modes', ['mode_id'], unique=False)
    op.create_table('mode_lines',
    sa.Column('mode_id', sa.UUID(), nullable=False),
    sa.Column('rf_min_mhz', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('rf_max_mhz', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('pw_min_us', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('pw_max_us', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('rf_range_matching', sa.Boolean(), nullable=False),
    sa.Column('pw_range_matching', sa.Boolean(), nullable=False),
    sa.Column('pri_range_matching', sa.Boolean(), nullable=False),
    sa.Column('rf_delta', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('pw_delta', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('pri_delta', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('pri_min_us', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('pri_max_us', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('jitter_min_us', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('jitter_max_us', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('pri_stagger_values_us', sa.ARRAY(sa.Numeric(precision=14, scale=4)), nullable=True),
    sa.Column('frame_time_delta_us', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('type_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dsl_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['mode_id'], ['modes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mode_lines_mode_id'), 'mode_lines', ['mode_id'], unique=True)
    op.create_table('test_record_modes',
    sa.Column('test_record_id', sa.UUID(), nullable=False),
    sa.Column('mode_id', sa.UUID(), nullable=False),
    sa.Column('link_type', sa.Enum('exercised', 'derived', name='testrecordmodelinktype'), server_default='exercised', nullable=False),
    sa.Column('result', sa.Enum('pass_', 'fail', 'partial', 'inconclusive', name='testresult'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('observed_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['mode_id'], ['modes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_record_id'], ['test_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_record_modes_test_record_id'), 'test_record_modes', ['test_record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_record_modes_test_record_id'), table_name='test_record_modes')
    op.drop_table('test_record_modes')
    op.drop_index(op.f('ix_mode_lines_mode_id'), table_name='mode_lines')
    op.drop_table('mode_lines')
    op.drop_index(op.f('ix_intercept_entry_modes_mode_id'), table_name='intercept_entry_modes')
    op.drop_index(op.f('ix_intercept_entry_modes_intercept_entry_id'), table_name='intercept_entry_modes')
    op.drop_table('intercept_entry_modes')
    op.drop_index(op.f('ix_modes_source_id'), table_name='modes')
    op.drop_index(op.f('ix_modes_generation_batch_id'), table_name='modes')
    op.drop_index(op.f('ix_modes_function_group_id'), table_name='modes')
    op.drop_index(op.f('ix_modes_ew_group_id'), table_name='modes')
    op.drop_table('modes')
    op.drop_index(op.f('ix_test_record_function_groups_test_record_id'), table_name='test_record_function_groups')
    op.drop_index(op.f('ix_test_record_function_groups_function_group_id'), table_name='test_record_function_groups')
    op.drop_table('test_record_function_groups')
    op.drop_index(op.f('ix_source_notes_source_id'), table_name='source_notes')
    op.drop_index(op.f('ix_source_notes_created_at'), table_name='source_notes')
    op.drop_table('source_notes')
    op.drop_index(op.f('ix_parameter_sequences_source_id'), table_name='parameter_sequences')
    op.drop_table('parameter_sequences')
    op.drop_index(op.f('ix_mode_generation_batches_source_id'), table_name='mode_generation_batches')
    op.drop_index(op.f('ix_mode_generation_batches_ew_group_id'), table_name='mode_generation_batches')
    op.drop_table('mode_generation_batches')
    op.drop_index(op.f('ix_mode_elements_source_id'), table_name='mode_elements')
    op.drop_table('mode_elements')
    op.drop_index(op.f('ix_ambiguity_findings_run_id'), table_name='ambiguity_findings')
    op.drop_table('ambiguity_findings')
    op.drop_index(op.f('ix_test_records_scope_id'), table_name='test_records')
    op.drop_table('test_records')
    op.drop_index(op.f('ix_sources_source_type'), table_name='sources')
    op.drop_index(op.f('ix_sources_import_batch_id'), table_name='sources')
    op.drop_index(op.f('ix_sources_group_id'), table_name='sources')
    op.drop_index(op.f('ix_sources_emitter_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_platform_emitter_links_platform_id'), table_name='platform_emitter_links')
    op.drop_table('platform_emitter_links')
    op.drop_index(op.f('ix_mdf_platform_links_mdf_id'), table_name='mdf_platform_links')
    op.drop_table('mdf_platform_links')
    op.drop_index(op.f('ix_intercept_notes_intercept_id'), table_name='intercept_notes')
    op.drop_index(op.f('ix_intercept_notes_created_at'), table_name='intercept_notes')
    op.drop_table('intercept_notes')
    op.drop_index(op.f('ix_intercept_entries_intercept_id'), table_name='intercept_entries')
    op.drop_index(op.f('ix_intercept_entries_created_at'), table_name='intercept_entries')
    op.drop_table('intercept_entries')
    op.drop_index(op.f('ix_ambiguity_runs_scope_type'), table_name='ambiguity_runs')
    op.drop_index(op.f('ix_ambiguity_runs_scope_id'), table_name='ambiguity_runs')
    op.drop_table('ambiguity_runs')
    op.drop_index(op.f('ix_platform_versions_platform_id'), table_name='platform_versions')
    op.drop_table('platform_versions')
    op.drop_index(op.f('ix_mdf_versions_mdf_id'), table_name='mdf_versions')
    op.drop_table('mdf_versions')
    op.drop_index(op.f('ix_mdf_notes_mdf_id'), table_name='mdf_notes')
    op.drop_index(op.f('ix_mdf_notes_created_at'), table_name='mdf_notes')
    op.drop_table('mdf_notes')
    op.drop_index(op.f('ix_intercepts_emitter_id'), table_name='intercepts')
    op.drop_table('intercepts')
    op.drop_index(op.f('ix_import_batches_emitter_id'), table_name='import_batches')
    op.drop_table('import_batches')
    op.drop_index(op.f('ix_function_groups_emitter_id'), table_name='function_groups')
    op.drop_table('function_groups')
    op.drop_index(op.f('ix_ew_groups_emitter_id'), table_name='ew_groups')
    op.drop_table('ew_groups')
    op.drop_index(op.f('ix_emitter_versions_emitter_id'), table_name='emitter_versions')
    op.drop_table('emitter_versions')
    op.drop_index(op.f('ix_emitter_notes_emitter_id'), table_name='emitter_notes')
    op.drop_index(op.f('ix_emitter_notes_created_at'), table_name='emitter_notes')
    op.drop_table('emitter_notes')
    op.drop_index(op.f('ix_audit_log_entity_type'), table_name='audit_log')
    op.drop_index('ix_audit_log_entity', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_emitter_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_platforms_name'), table_name='platforms')
    op.drop_table('platforms')
    op.drop_index(op.f('ix_mdfs_name'), table_name='mdfs')
    op.drop_index(op.f('ix_mdfs_customer_id'), table_name='mdfs')
    op.drop_table('mdfs')
    op.drop_index(op.f('ix_emitters_name'), table_name='emitters')
    op.drop_index(op.f('ix_emitters_forked_from_version_id'), table_name='emitters')
    op.drop_index(op.f('ix_emitters_forked_from_emitter_id'), table_name='emitters')
    op.drop_index(op.f('ix_emitters_checked_out_by_id'), table_name='emitters')
    op.drop_table('emitters')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('source_groups')
    op.drop_table('customers')
    # ### end Alembic commands ###
