"""test_record_mode_observed_values

Revision ID: e095882048be
Revises: 994ef215d663
Create Date: 2026-08-28 15:00:25.380543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e095882048be'
down_revision: Union[str, None] = '994ef215d663'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_record_modes', sa.Column('observed_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_record_modes', 'observed_values')
    # ### end Alembic commands ###
