"""phase4_platforms

Revision ID: e6cb2cbe3435
Revises: 9e5617eaa780
Create Date: 2026-08-24 07:57:15.906826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e6cb2cbe3435'
down_revision: Union[str, None] = '9e5617eaa780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platforms',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platforms_name'), 'platforms', ['name'], unique=True)
    op.create_table('platform_versions',
    sa.Column('platform_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_id', 'version_number', name='uq_platform_version_number')
    )
    op.create_index(op.f('ix_platform_versions_platform_id'), 'platform_versions', ['platform_id'], unique=False)
    op.create_table('platform_emitter_links',
    sa.Column('platform_id', sa.UUID(), nullable=False),
    sa.Column('emitter_id', sa.UUID(), nullable=False),
    sa.Column('emitter_version_id', sa.UUID(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['emitter_id'], ['emitters.id'], ),
    sa.ForeignKeyConstraint(['emitter_version_id'], ['emitter_versions.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_id', 'emitter_id', name='uq_platform_emitter')
    )
    op.create_index(op.f('ix_platform_emitter_links_platform_id'), 'platform_emitter_links', ['platform_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_platform_emitter_links_platform_id'), table_name='platform_emitter_links')
    op.drop_table('platform_emitter_links')
    op.drop_index(op.f('ix_platform_versions_platform_id'), table_name='platform_versions')
    op.drop_table('platform_versions')
    op.drop_index(op.f('ix_platforms_name'), table_name='platforms')
    op.drop_table('platforms')
    # ### end Alembic commands ###
