"""add emitter_notes and source_notes tables, drop notes columns

Revision ID: eb0437ec8ea8
Revises: 6ef6d282f7c4
Create Date: 2026-09-14 15:26:04.854300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'eb0437ec8ea8'
down_revision: Union[str, None] = '6ef6d282f7c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emitter_notes',
    sa.Column('emitter_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['emitter_id'], ['emitters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emitter_notes_created_at'), 'emitter_notes', ['created_at'], unique=False)
    op.create_index(op.f('ix_emitter_notes_emitter_id'), 'emitter_notes', ['emitter_id'], unique=False)
    op.create_table('source_notes',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_notes_created_at'), 'source_notes', ['created_at'], unique=False)
    op.create_index(op.f('ix_source_notes_source_id'), 'source_notes', ['source_id'], unique=False)

    # Carry forward any existing single-blob notes as the first entry in each
    # entity's new append-only log, rather than silently discarding them.
    # author_id is left null — we have no record of who originally wrote the
    # free-text blob; created_at uses the entity's own updated_at as the best
    # available approximation of when it was last touched.
    op.execute(
        """
        INSERT INTO emitter_notes (id, emitter_id, author_id, body, created_at)
        SELECT gen_random_uuid(), id, NULL, notes, updated_at
        FROM emitters
        WHERE notes IS NOT NULL AND notes != ''
        """
    )
    op.execute(
        """
        INSERT INTO source_notes (id, source_id, author_id, body, created_at)
        SELECT gen_random_uuid(), id, NULL, notes, updated_at
        FROM sources
        WHERE notes IS NOT NULL AND notes != ''
        """
    )

    op.drop_column('emitters', 'notes')
    op.drop_column('sources', 'notes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('emitters', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))

    # Best-effort: collapse each entity's log back into a single blob using
    # its most recent note. Older entries are not recoverable in this
    # direction — this is a lossy downgrade by nature of the schema change.
    op.execute(
        """
        UPDATE emitters SET notes = latest.body
        FROM (
            SELECT DISTINCT ON (emitter_id) emitter_id, body
            FROM emitter_notes
            ORDER BY emitter_id, created_at DESC
        ) AS latest
        WHERE emitters.id = latest.emitter_id
        """
    )
    op.execute(
        """
        UPDATE sources SET notes = latest.body
        FROM (
            SELECT DISTINCT ON (source_id) source_id, body
            FROM source_notes
            ORDER BY source_id, created_at DESC
        ) AS latest
        WHERE sources.id = latest.source_id
        """
    )

    op.drop_index(op.f('ix_source_notes_source_id'), table_name='source_notes')
    op.drop_index(op.f('ix_source_notes_created_at'), table_name='source_notes')
    op.drop_table('source_notes')
    op.drop_index(op.f('ix_emitter_notes_emitter_id'), table_name='emitter_notes')
    op.drop_index(op.f('ix_emitter_notes_created_at'), table_name='emitter_notes')
    op.drop_table('emitter_notes')
    # ### end Alembic commands ###
