"""add source_type to sources

Revision ID: ec2859f3a031
Revises: update_source_cols_rev
Create Date: 2026-09-11 10:20:52.339521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ec2859f3a031'
down_revision: Union[str, None] = 'update_source_cols_rev'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('source_type', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_sources_source_type'), 'sources', ['source_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sources_source_type'), table_name='sources')
    op.drop_column('sources', 'source_type')
    # ### end Alembic commands ###
