"""test_record_simulation_created_date

Revision ID: ecb2e5dedaa9
Revises: d3265fb54f12
Create Date: 2026-08-27 12:59:40.604621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ecb2e5dedaa9'
down_revision: Union[str, None] = 'd3265fb54f12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_records', sa.Column('simulation_created_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_records', 'simulation_created_date')
    # ### end Alembic commands ###
