"""audit_log_emitter_rollup

Revision ID: f1a2b3c4d5e6
Revises: b0413a33e335
Create Date: 2026-08-28 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'f1a2b3c4d5e6'
down_revision: Union[str, None] = 'b0413a33e335'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_log', sa.Column('emitter_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(
        'audit_log_emitter_id_fkey', 'audit_log', 'emitters', ['emitter_id'], ['id'], ondelete='SET NULL'
    )
    op.create_index(op.f('ix_audit_log_emitter_id'), 'audit_log', ['emitter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_log_emitter_id'), table_name='audit_log')
    op.drop_constraint('audit_log_emitter_id_fkey', 'audit_log', type_='foreignkey')
    op.drop_column('audit_log', 'emitter_id')
    # ### end Alembic commands ###
