"""add emitter forked_at_version_number

Revision ID: f47516fcb470
Revises: d68a4d14b7c2
Create Date: 2026-09-22 06:54:21.843068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f47516fcb470'
down_revision: Union[str, None] = 'd68a4d14b7c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emitters', sa.Column('forked_at_version_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emitters', 'forked_at_version_number')
    # ### end Alembic commands ###
